### ISSUE TITLE
/bin/sh: 1: barman: not found

### ISSUE THREAD

**Issue by luzfcb** [modcloth/ansible-role-modcloth-barman#8]
hello, I am trying to use that role, and I'm having the following problem:

```
barman@dbslave:/var/log/barman$ cat backup.log 
Tue Jun  2 18:02:01 BRT 2015
/bin/sh: 1: barman: not found


barman@dbslave:/var/log/barman$ barman check solar_db
Server solar:
    ssh: FAILED (return code: 255)
    PostgreSQL: OK
    archive_mode: OK
    archive_command: OK
    directories: OK
    retention policy settings: OK
    backup maximum age: OK (no last_backup_maximum_age provided)
    compression settings: OK
    minimum redundancy requirements: OK (have 0 backups, expected at least 0)

```

```

playbook: 
- hosts: all
  sudo: True
  roles:
  - role: modcloth.barman
    barman_backup_schedule: '2 * * * *'
    barman_upstreams:
      - name: "solar_db"
        ssh_user: "db_server_user"
        hostname: "10.60.20.230"
```

do you have any idea what I'm doing wrong?
